In [1]:
#MATRIX OPERATIONS
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=A+B
D=A-B
E=A*B
F=np.dot(A,B)
G=A.T
print("Addition:\n",C)
print("Subtraction:\n",D)
print("Multiplication(element-wise):\n",E)
print("Multiplication(matrix):\n",F)
print("Transpose:\n",G)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication(element-wise):
 [[ 5 12]
 [21 32]]
Multiplication(matrix):
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


In [2]:
#with SVD
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed=np.dot(U[:,:n_components], np.dot(np.diag(S[:n_components]) ,VT[:n_components,:]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix(with reduced dimensions):")
print("\n",X_reconstructed)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions):

 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
